'use strict';
let data, page = 1;
const main = document.querySelector('main');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId = id => data.people.find(p => p.id === id);
const personName = id => byId(id)?.name || data.externalPeople[id] || id;
const link = id => byId(id) ? `<a href="#person/${encodeURIComponent(id)}">${esc(personName(id))}</a>` : `${esc(personName(id))} <small>(referenced person; no profile in workbook)</small>`;
const initials = name => name.split(' ').slice(0,2).map(n=>n[0]).join('');
const clans = () => [...new Set(data.people.map(p=>p.clan))].sort();
const heading = (title, sub, eyebrow='YOUR SHARED ROOTS') => `<p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="sub">${sub}</p>`;
const card = p => `<a class="person" href="#person/${p.id}"><div class="avatar">${esc(initials(p.name))}</div><h3>${esc(p.name)}</h3><p>${esc(p.clan)} lineage · ${esc(p.city)}</p><div class="origin">Roots in ${esc(p.origin)}</div><div class="card-bottom"><span>${data.relationships.filter(r=>r.from===p.id||r.to===p.id).length} relationship records</span><span>View profile ↗</span></div></a>`;
const eventCard = e => `<a class="event" href="#event/${e.id}"><div class="event-symbol">◇</div><div><h3>${esc(e.name)}</h3><p>${esc(e.location)}</p><p>${e.people.length} seeded participants · Date not set</p></div></a>`;
const edges = rows => rows.map(r=>`<div class="edge">${link(r.from)}<span class="edge-type">${esc(r.type.toLowerCase().replaceAll('_',' '))} →</span>${link(r.to)}<small>${esc(r.note)}</small></div>`).join('') || '<p class="empty">No relationship records found.</p>';
const forest = `<svg class="forest" viewBox="0 0 440 300" aria-hidden="true"><path d="M0 275Q150 215 440 265V300H0" fill="#d0dbba"/><g stroke="#6c8056" fill="none" stroke-width="3"><path d="M258 290V79m0 94-64-63m64 101 72-73m-72 103-97-57m97-54 44-48"/><path d="M118 291V166m0 68-37-43m37 67 40-31"/><path d="M378 289V164m0 57-30-34m30 64 35-28"/></g><g fill="#9dae7f"><ellipse cx="224" cy="95" rx="37" ry="20" transform="rotate(42 224 95)"/><ellipse cx="285" cy="73" rx="40" ry="22" transform="rotate(-48 285 73)"/><ellipse cx="314" cy="132" rx="38" ry="21" transform="rotate(-35 314 132)"/><ellipse cx="191" cy="172" rx="42" ry="22" transform="rotate(30 191 172)"/></g><g fill="#bdcba3"><ellipse cx="99" cy="182" rx="30" ry="17" transform="rotate(40 99 182)"/><ellipse cx="141" cy="216" rx="27" ry="16" transform="rotate(-30 141 216)"/><ellipse cx="365" cy="176" rx="28" ry="16" transform="rotate(40 365 176)"/><ellipse cx="397" cy="214" rx="28" ry="16" transform="rotate(-35 397 214)"/></g><g fill="#f7f8f2"><circle cx="195" cy="64" r="4"/><circle cx="350" cy="87" r="5"/><circle cx="79" cy="137" r="4"/></g></svg>`;
function home(){main.innerHTML = heading('A little closer. A little more connected.','Discover the people, stories, and shared roots that bring us together.','WELCOME TO YOUR COMMUNITY')+`<section class="hero"><div class="hero-copy"><p class="eyebrow">STRONG ROOTS. MEANINGFUL CONNECTIONS.</p><h2>Every person is a story.<br>Together, we’re a forest.</h2><p>Find familiar faces, explore your connections, and make room for new ones.</p><a class="button" href="#people">Explore the community <span aria-hidden="true">↗</span></a></div>${forest}</section><section class="stats" aria-label="Community statistics">${[[data.people.length,'Demo members'],[data.relationships.length,'Relationship records'],[clans().length,'Lineages'],[data.events.length,'Story events']].map(([n,l])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join('')}</section><div class="section-head"><h2>Meet your community</h2><a href="#people">View everyone →</a></div><div class="cards">${data.people.slice(0,3).map(card).join('')}</div><div class="two-col"><section><div class="section-head"><h2>Gather around a story</h2><a href="#events">All events →</a></div>${data.events.slice(0,2).map(eventCard).join('')}</section><section><div class="section-head"><h2>A shared beginning</h2></div><div class="note"><span class="eyebrow">THE RAMAYANA COLLECTION</span><p>Explore a community through 44 characters and their connections. Modern locations and preferences are synthetic demonstration data.</p><a href="#about">Learn about this demo →</a></div></section></div>`;}
function people(){main.innerHTML=heading('People, with a connection.','Explore the Ramayana collection by name, shared roots, or lineage.')+`<div class="filters"><input id="search" aria-label="Search people" placeholder="Search names, aliases, roots, languages…"><select id="clan" aria-label="Filter by lineage"><option value="">All lineages</option>${clans().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="results" aria-live="polite"></div>`; page=1; document.querySelector('#search').oninput=document.querySelector('#clan').onchange=()=>{page=1;results();};results();}
function results(){const q=document.querySelector('#search').value.toLowerCase().trim(), clan=document.querySelector('#clan').value;const list=data.people.filter(p=>(!clan||p.clan===clan)&&[p.name,p.aliases,p.origin,p.city,p.languages].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(list.length/12));document.querySelector('#results').innerHTML=`<p class="results">${list.length} people · Modern locations are synthetic</p><div class="cards">${list.slice((page-1)*12,page*12).map(card).join('')||'<p class="empty">No people match. Try another name or lineage.</p>'}</div><div class="pagination"><button class="button secondary" id="prev" ${page===1?'disabled':''}>Previous</button><span>Page ${page} of ${pages}</span><button class="button secondary" id="next" ${page===pages?'disabled':''}>Next</button></div>`;document.querySelector('#prev').onclick=()=>{page--;results();};document.querySelector('#next').onclick=()=>{page++;results();};}
function connections(){main.innerHTML=heading('The ties that bring us together.','Explore directional relationships from the workbook. Source notes are preserved.')+`<div class="filters"><select id="connection-person" aria-label="Choose a person">${data.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div id="edges"></div>`;const select=document.querySelector('select');const render=()=>document.querySelector('#edges').innerHTML=edges(data.relationships.filter(r=>r.from===select.value||r.to===select.value));select.onchange=render;render();}
function groups(){main.innerHTML=heading('Different roots. A shared forest.','Browse lineages recorded in the workbook. These collections are not membership groups.')+`<div class="cards">${clans().map(c=>`<a class="group" href="#lineage/${encodeURIComponent(c)}"><p class="eyebrow">LINEAGE COLLECTION</p><h2>${esc(c)}</h2><p class="sub">${data.people.filter(p=>p.clan===c).length} people</p><span>Explore people →</span></a>`).join('')}</div>`;}
function events(calendar=false){main.innerHTML=heading(calendar?'A place for every gathering.':'Gather around a story.',calendar?'The workbook does not specify dates. All eight events are currently unscheduled.':'Explore story events and their seeded participants.')+(calendar?'<div class="note">Unscheduled events appear below. Calendar downloads will be available when actual event dates and timezones are supplied.</div>':'')+`<div class="section-head"><h2>${calendar?'Unscheduled':'The event collection'}</h2><span class="tag">8 demo events</span></div>`+data.events.map(eventCard).join('');}
function about(){main.innerHTML=heading('A community starts with a connection.','Tree in the Forest · A public demonstration')+`<div class="about"><h2>One tree, with room to grow</h2><p>This project explores the community-directory vision in CODEX_PROMPT.md: people connected through relationships, shared roots, and events. This GitHub Pages edition is a static, publicly accessible demonstration.</p><h2>About the source</h2><p>The supplied Ramayana workbook contains 44 demo profiles, 80 relationship records, 8 events, and 47 registration records. Modern US locations, contacts, education, employment, and preferences are synthetic. Relationships may vary across traditions; the original notes appear alongside each connection.</p><p>Gautama is referenced in one relationship but has no profile in the source workbook. The relationship is retained as a reference, without inventing a profile. Events have no dates and are shown as unscheduled.</p><h2>Privacy and scope</h2><p>The website exports only selected demo fields. Contact details, street addresses, dietary preferences, and individual registration logistics are excluded from the website data. Demo event saves stay in this browser only and are not registrations.</p><p>Private accounts, profile editing, real RSVPs, membership groups, organizer tools, and access control need an authenticated backend. They are not implemented by this public static site. Do not add real member information to the public dataset.</p><button class="button secondary" id="clear-saves">Clear saved demo events</button><p id="clear-status" role="status"></p></div>`;document.querySelector('#clear-saves').onclick=()=>{try{localStorage.removeItem('forest-saved');document.querySelector('#clear-status').textContent='Saved demo events cleared.';}catch{document.querySelector('#clear-status').textContent='Browser storage is unavailable.';}};}
function saved(){try{return JSON.parse(localStorage.getItem('forest-saved')||'[]');}catch{return [];}}
function detail(kind,id){const p=kind==='person'?byId(id):data.events.find(e=>e.id===id);if(!p){main.innerHTML=heading('Page not found.','<a href="#home">Return to the community →</a>');return;}if(kind==='person'){main.innerHTML=heading(esc(p.name),'A profile from the Ramayana demo collection.')+`<div class="note"><dl>${[['Lineage',p.clan],['Ancestral home',p.origin],['Demo city',p.city],['Languages',p.languages],['Aliases',p.aliases||'None recorded']].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p>Modern profile details are synthetic. This is not a historical biography.</p></div><div class="section-head"><h2>Family & connections</h2></div>${edges(data.relationships.filter(r=>r.from===id||r.to===id))}`;}else{main.innerHTML=heading(esc(p.name),esc(p.location),'STORY EVENT')+`<div class="note"><p>Date not set · ${p.people.length} seeded participants</p><p>This is a demo event from the workbook. Saving it is a browser bookmark, not an RSVP.</p><button class="button" id="save-event">${saved().includes(id)?'Remove saved event':'Save demo event'}</button><p id="save-status" role="status"></p></div><div class="section-head"><h2>People in this story</h2></div><div class="cards">${p.people.map(byId).filter(Boolean).map(card).join('')}</div>`;document.querySelector('#save-event').onclick=()=>{let ids=saved();ids=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];try{localStorage.setItem('forest-saved',JSON.stringify(ids));document.querySelector('#save-event').textContent=ids.includes(id)?'Remove saved event':'Save demo event';document.querySelector('#save-status').textContent=ids.includes(id)?'Saved in this browser.':'Removed from saved events.';}catch{document.querySelector('#save-status').textContent='Your browser does not allow local storage.';}};}}
function route(){const [view='home',raw='']=location.hash.slice(1).split('/');let id;try{id=decodeURIComponent(raw);}catch{id='';}document.querySelectorAll('nav a').forEach(a=>{const active=a.hash===`#${view}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(view==='home'||!view)home();else if(view==='people')people();else if(view==='connections')connections();else if(view==='groups')groups();else if(view==='events')events();else if(view==='calendar')events(true);else if(view==='about')about();else if(view==='person'||view==='event')detail(view,id);else if(view==='lineage'){main.innerHTML=heading(esc(id),'People connected by a shared lineage in the demo workbook.')+`<div class="cards">${data.people.filter(p=>p.clan===id).map(card).join('')||'<p>No matching lineage.</p>'}</div>`;}else main.innerHTML=heading('Page not found.','<a href="#home">Return home →</a>');document.title=`${main.querySelector('h1')?.textContent||'Community'} · Tree in the Forest`;window.scrollTo(0,0);}
fetch('./data.json').then(r=>{if(!r.ok)throw Error('Unable to load data');return r.json();}).then(d=>{data=d;route();window.addEventListener('hashchange',()=>{route();main.focus();});}).catch(()=>{main.innerHTML='<h1>Unable to load the community.</h1><p>Please refresh. For local development, serve the site over HTTP as described in README.md.</p>';});
