(function(root){
  'use strict';
  const assets=new Map(),maps=new WeakMap();
  const provinceNames={BC:'British Columbia',AB:'Alberta',SK:'Saskatchewan',MB:'Manitoba',ON:'Ontario',QC:'Quebec',NB:'New Brunswick',NS:'Nova Scotia',PE:'Prince Edward Island',NL:'Newfoundland and Labrador'};
  function loadAsset(url,css=false){if(!css&&root.L)return Promise.resolve();if(css&&document.querySelector(`link[href="${url}"]`))return Promise.resolve();if(assets.has(url))return assets.get(url);const pending=new Promise((resolve,reject)=>{const el=document.createElement(css?'link':'script');if(css){el.rel='stylesheet';el.href=url;}else el.src=url;el.onload=resolve;el.onerror=()=>{assets.delete(url);reject(Error('Map asset unavailable'));};document.head.appendChild(el);});assets.set(url,pending);return pending;}
  function boundaryData(){const key='chapter-boundaries';if(assets.has(key))return assets.get(key);const pending=Promise.all(['./chapter-boundaries-us.geojson','./chapter-boundaries-canada.geojson'].map(url=>fetch(url).then(response=>{if(!response.ok)throw Error('Boundary data unavailable');return response.json();}))).then(([us,canada])=>({us,canada}));assets.set(key,pending);return pending;}
  function featureCollection(chapter,data){const national=chapter.id==='national',us=national?data.us.features:data.us.features.filter(feature=>chapter.states?.includes(feature.properties.STUSPS)),wanted=new Set((chapter.provinces||[]).map(code=>provinceNames[code])),canada=national?data.canada.features:data.canada.features.filter(feature=>wanted.has(feature.properties.name));return {type:'FeatureCollection',features:[...us,...canada]};}
  async function paint(container,chapter){maps.get(container)?.remove();container.innerHTML='<div class="chapter-map-loading" role="status">Drawing state and province boundaries…</div>';try{const [, ,data]=await Promise.all([loadAsset('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',true),loadAsset('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'),boundaryData()]);container.innerHTML='';const instance=L.map(container,{scrollWheelZoom:false}).setView([42,-98],3),style=getComputedStyle(document.documentElement),action=style.getPropertyValue('--action').trim()||'#153eaa',accent=style.getPropertyValue('--accent').trim()||'#ff9933';maps.set(container,instance);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:8,attribution:'© OpenStreetMap contributors · boundaries: U.S. Census and public Canadian province data'}).addTo(instance);const layer=L.geoJSON(featureCollection(chapter,data),{style:{color:action,weight:2,fillColor:accent,fillOpacity:.24}}).addTo(instance),bounds=layer.getBounds();if(bounds.isValid()){instance.fitBounds(bounds,{padding:[22,22],maxZoom:chapter.id==='national'?3:5});L.tooltip({permanent:true,direction:'center',className:'chapter-map-label'}).setLatLng(bounds.getCenter()).setContent(chapter.name).addTo(instance);}return instance;}catch(error){container.innerHTML='<div class="chapter-map-error note" role="alert"><strong>The map could not load.</strong><span>Boundary data or the map library is unavailable.</span><button class="button secondary" type="button">Retry map</button></div>';container.querySelector('button')?.addEventListener('click',()=>paint(container,chapter),{once:true});return null;}}
  async function render(id){const main=document.querySelector('#main'),chapter=root.ChapterCore?.chapters.find(c=>c.id===id)||root.ChapterCore?.chapters[0];if(!main||!chapter)return;main.innerHTML=`<p class="eyebrow">CHAPTER TERRITORY</p><h1>${chapter.name}</h1><p class="sub">This service area follows the assigned state and province boundaries. National displays the United States and Canada together.</p><div id="chapter-map" class="locality-map" role="img" aria-label="Map of ${chapter.name} service area"></div><p class="map-disclaimer">For community navigation; not a statement of legal jurisdiction.</p><p class="results"><a href="#chapter/${chapter.id}">← Back to ${chapter.name}</a></p>`;await paint(document.querySelector('#chapter-map'),chapter);}
  async function renderInline(id){const chapter=root.ChapterCore?.chapters.find(c=>c.id===id)||root.ChapterCore?.chapters[0],container=document.querySelector('#chapter-inline-map');if(!chapter||!container)return;container.setAttribute('aria-busy','true');await paint(container,chapter);container.removeAttribute('aria-busy');}
  root.ChapterMap={render,renderInline,featureCollection};
})(globalThis);
