(function(root){
  'use strict';
  const chapters=[
    {id:'national',name:'IMRC National',country:'United States & Canada',theme:'Peacock',committees:['National Programs','Membership & Chapters','Finance & Governance'],initiatives:['IMRC Convention 2028','National mentorship network','Shared community calendar'],leadership:[['President','Asha Mehta'],['Vice President','Vikram Shah'],['Treasurer','Neelam Rao'],['Secretary','Ravi Patel']]},
    {id:'northeast',name:'Northeast Chapter',country:'United States',theme:'Jodhpur',matches:['Northeast','New England'],committees:['Welcome & Membership','Cultural Programs','Youth'],initiatives:['Spring family gathering','New member welcome'],leadership:[['President','Maya Shah'],['Vice President','Arjun Mehta'],['Treasurer','Nisha Patel'],['Secretary','Kiran Rao']]},
    {id:'mideast',name:'Mid-Atlantic Chapter',country:'United States',theme:'Jodhpur',matches:['Mideast'],committees:['Events','Community Care','Professional Network'],initiatives:['Regional dinner','Volunteer exchange'],leadership:[['President','Ritu Mehta'],['Vice President','Sameer Shah'],['Treasurer','Pooja Rao'],['Secretary','Dev Patel']]},
    {id:'midwest',name:'Midwest Chapter',country:'United States',theme:'Udaipur',matches:['Midwest'],committees:['Events','Finance','Youth & Families'],initiatives:['Summer picnic','Student support'],leadership:[['President','Anita Shah'],['Vice President','Raj Mehta'],['Treasurer','Leena Patel'],['Secretary','Mohan Rao']]},
    {id:'southwest',name:'Southwest Chapter',country:'United States',theme:'Jaipur',matches:['Southwest'],committees:['Programs','Membership','Community Care'],initiatives:['Dallas gathering','Health initiative'],leadership:[['President','Kavita Shah'],['Vice President','Amit Mehta'],['Treasurer','Reena Rao'],['Secretary','Suresh Patel']]},
    {id:'southeast',name:'Southeast Chapter',country:'United States',theme:'Jaisalmer',matches:['Southeast'],committees:['Events','Outreach','Cultural Programs'],initiatives:['Atlanta meetup','Heritage workshop'],leadership:[['President','Meera Rao'],['Vice President','Nitin Shah'],['Treasurer','Swati Mehta'],['Secretary','Jay Patel']]},
    {id:'west-coast',name:'West Coast Chapter',country:'United States',theme:'Peacock',matches:['West Coast North','West Coast South'],committees:['Programs','Technology','Membership'],initiatives:['Bay Area gathering','Pacific welcome'],leadership:[['President','Priya Shah'],['Vice President','Nikhil Rao'],['Treasurer','Sunita Patel'],['Secretary','Rohan Mehta']]},
    {id:'canada-east',name:'Canada East & Central Chapter',country:'Canada',theme:'Peacock',matches:['Canada East & Central'],committees:['Member Care','Events','Youth'],initiatives:['Ontario welcome','Heritage circle'],leadership:[['President','Alka Shah'],['Vice President','Manish Rao'],['Treasurer','Deepa Patel'],['Secretary','Vivek Mehta']]},
    {id:'canada-west',name:'Canada West Chapter',country:'Canada',theme:'Jaisalmer',matches:['Canada West'],committees:['Events','Outreach','Membership'],initiatives:['Prairie gathering','Western welcome'],leadership:[['President','Sonal Mehta'],['Vice President','Ashwin Shah'],['Treasurer','Rekha Rao'],['Secretary','Tarun Patel']]}
  ];
  const cityFallback={'New York, NY':'northeast','Boston, MA':'northeast','Washington, DC':'mideast','Chicago, IL':'midwest','Dallas, TX':'southwest','Houston, TX':'southwest','Atlanta, GA':'southeast','San Francisco, CA':'west-coast','Los Angeles, CA':'west-coast','Toronto, ON, Canada':'canada-east','Montreal, QC, Canada':'canada-east','Vancouver, BC, Canada':'canada-west'};
  function forPerson(person){if(!person)return chapters[0];const city=String(person.city||''),state=city.split(',').slice(-1)[0].trim(),byAddress=cityFallback[city]||(/Canada/i.test(city)?(state==='BC'||state==='AB'||state==='SK'||state==='MB'?'canada-west':'canada-east'):(['TX','AZ','CO','NM'].includes(state)?'southwest':['IL','OH','MI','MN','WI'].includes(state)?'midwest':['NY','MA','CT','RI','NH','VT','ME'].includes(state)?'northeast':['GA','FL','NC','SC','TN','AL'].includes(state)?'southeast':['CA','WA','OR'].includes(state)?'west-coast':state==='DC'||state==='MD'||state==='NJ'?'mideast':''));return chapters.find(c=>c.id===byAddress)||chapters.find(c=>c.matches?.includes(person.chapter))||chapters[0];}
  function decorate(data){const node=document.querySelector('#chapter-context');if(!node)return;let person=null;try{const s=JSON.parse(localStorage.getItem('forest-community-v1')||'{}').session;person=data.people.find(p=>p.id===s.personaId);}catch{}const chapter=forPerson(person);node.innerHTML=`<a href="#chapter/${chapter.id}"><strong>${chapter.name}</strong> · ${person?.city||'National view'}</a>`;}
  root.ChapterCore={chapters,forPerson,decorate};
})(globalThis);
