(function(root){
  'use strict';
  const regions={
    northeast:[[47,-80],[47,-66],[39,-66],[39,-80]],mideast:[[43,-82],[43,-72],[35,-72],[35,-82]],midwest:[[49,-104],[49,-82],[36,-82],[36,-104]],southwest:[[37,-114],[37,-94],[25,-94],[25,-114]],southeast:[[37,-94],[37,-75],[24,-75],[24,-94]],'west-coast':[[49,-125],[49,-114],[32,-114],[32,-125]],national:[[50,-125],[50,-66],[24,-66],[24,-125]],'canada-east':[[60,-95],[60,-52],[42,-52],[42,-95]],'canada-west':[[60,-140],[60,-95],[42,-95],[42,-140]]
  };
  let map;
  function load(url,css=false){return new Promise((resolve,reject)=>{const el=document.createElement(css?'link':'script');if(css){el.rel='stylesheet';el.href=url;}else el.src=url;el.onload=resolve;el.onerror=reject;document.head.appendChild(el);});}
  async function paint(container,chapter){try{await Promise.all([load('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',true),load('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js')]);const instance=L.map(container,{scrollWheelZoom:false}).setView([39.8,-98.6],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:8,attribution:'© OpenStreetMap contributors'}).addTo(instance);const points=regions[chapter.id]||regions.national;L.polygon(points,{color:'#c22303',weight:3,fillColor:'#faa622',fillOpacity:.22}).addTo(instance).bindTooltip(chapter.name,{permanent:true,direction:'center'});instance.fitBounds(points,{padding:[20,20]});return instance;}catch{return null;}}
  async function render(id){const main=document.querySelector('#main'),chapter=root.ChapterCore?.chapters.find(c=>c.id===id)||root.ChapterCore?.chapters[0];if(!main||!chapter)return;main.innerHTML=`<p class="eyebrow">CHAPTER TERRITORY</p><h1>${chapter.name}</h1><p class="sub">A schematic service area for the chapter selected from the member’s home address. Boundaries are illustrative, not legal jurisdictions.</p><div id="chapter-map" class="locality-map" role="img" aria-label="Map of ${chapter.name} service area"></div><p class="results"><a href="#chapter/${chapter.id}">← Back to ${chapter.name}</a></p>`;if(!await paint(document.querySelector('#chapter-map'),chapter))document.querySelector('#chapter-map')?.insertAdjacentHTML('afterend','<p class="note">Unable to load the chapter map. Check your connection and reopen this page to retry.</p>');}
  async function renderInline(id){const chapter=root.ChapterCore?.chapters.find(c=>c.id===id)||root.ChapterCore?.chapters[0],container=document.querySelector('#chapter-inline-map');if(!chapter||!container)return;container.innerHTML='<p class="results">Loading chapter territory…</p>';const instance=await paint(container,chapter);if(!instance)container.innerHTML='<p class="note">Chapter map unavailable. Reopen the page to retry.</p>';}
  root.ChapterMap={render,renderInline};
})(globalThis);
