(function(root){
  'use strict';
  const chapters=[
    {id:'national',name:'IMRC National',country:'United States & Canada',theme:'Indian Flag',committees:['National Programs','Membership & Chapters','Finance & Governance'],initiatives:['IMRC Convention 2028','National mentorship network','Shared community calendar'],leadership:[['President','Asha Mehta'],['Vice President','Vikram Shah'],['Treasurer','Neelam Rao'],['Secretary','Ravi Patel']]},
    {id:'northeast',name:'Northeast Chapter',country:'United States',theme:'Jodhpur',states:['CT','ME','MA','NH','NY','PA','RI','VT'],matches:['Northeast','New England'],committees:['Welcome & Membership','Cultural Programs','Youth'],initiatives:['Spring family gathering','New member welcome'],leadership:[['President','Maya Shah'],['Vice President','Arjun Mehta'],['Treasurer','Nisha Patel'],['Secretary','Kiran Rao']]},
    {id:'mideast',name:'Mid-Atlantic Chapter',country:'United States',theme:'Jodhpur',states:['DE','DC','MD','NJ','VA','WV'],matches:['Mideast'],committees:['Events','Community Care','Professional Network'],initiatives:['Regional dinner','Volunteer exchange'],leadership:[['President','Ritu Mehta'],['Vice President','Sameer Shah'],['Treasurer','Pooja Rao'],['Secretary','Dev Patel']]},
    {id:'midwest',name:'Midwest Chapter',country:'United States',theme:'Udaipur',states:['IL','IN','IA','KS','MI','MN','MO','NE','ND','OH','SD','WI'],matches:['Midwest'],committees:['Events','Finance','Youth & Families'],initiatives:['Summer picnic','Student support'],leadership:[['President','Anita Shah'],['Vice President','Raj Mehta'],['Treasurer','Leena Patel'],['Secretary','Mohan Rao']]},
    {id:'southwest',name:'Southwest Chapter',country:'United States',theme:'Jaipur',states:['AZ','CO','MT','NM','OK','TX','UT','WY'],matches:['Southwest'],committees:['Programs','Membership','Community Care'],initiatives:['Dallas gathering','Health initiative'],leadership:[['President','Kavita Shah'],['Vice President','Amit Mehta'],['Treasurer','Reena Rao'],['Secretary','Suresh Patel']]},
    {id:'southeast',name:'Southeast Chapter',country:'United States',theme:'Jaisalmer',states:['AL','AR','FL','GA','KY','LA','MS','NC','SC','TN'],matches:['Southeast'],committees:['Events','Outreach','Cultural Programs'],initiatives:['Atlanta meetup','Heritage workshop'],leadership:[['President','Meera Rao'],['Vice President','Nitin Shah'],['Treasurer','Swati Mehta'],['Secretary','Jay Patel']]},
    {id:'west-coast',name:'West Coast Chapter',country:'United States',theme:'Peacock',states:['AK','CA','HI','ID','NV','OR','WA'],matches:['West Coast North','West Coast South'],committees:['Programs','Technology','Membership'],initiatives:['Bay Area gathering','Pacific welcome'],leadership:[['President','Priya Shah'],['Vice President','Nikhil Rao'],['Treasurer','Sunita Patel'],['Secretary','Rohan Mehta']]},
    {id:'canada-east',name:'Canada East & Central Chapter',country:'Canada',theme:'Peacock',provinces:['ON','QC','NB','NS','PE','NL'],matches:['Canada East & Central'],committees:['Member Care','Events','Youth'],initiatives:['Ontario welcome','Heritage circle'],leadership:[['President','Alka Shah'],['Vice President','Manish Rao'],['Treasurer','Deepa Patel'],['Secretary','Vivek Mehta']]},
    {id:'canada-west',name:'Canada West Chapter',country:'Canada',theme:'Jaisalmer',provinces:['BC','AB','SK','MB'],matches:['Canada West'],committees:['Events','Outreach','Membership'],initiatives:['Prairie gathering','Western welcome'],leadership:[['President','Sonal Mehta'],['Vice President','Ashwin Shah'],['Treasurer','Rekha Rao'],['Secretary','Tarun Patel']]}
  ];
  const cityFallback={'New York, NY':'northeast','Boston, MA':'northeast','Washington, DC':'mideast','Chicago, IL':'midwest','Dallas, TX':'southwest','Houston, TX':'southwest','Atlanta, GA':'southeast','San Francisco, CA':'west-coast','Los Angeles, CA':'west-coast','Toronto, ON, Canada':'canada-east','Montreal, QC, Canada':'canada-east','Vancouver, BC, Canada':'canada-west'};
  function forPerson(person){if(!person)return chapters[0];const city=String(person.city||''),parts=city.split(',').map(s=>s.trim()),region=/Canada/i.test(city)?parts.at(-2):parts.at(-1),byAddress=cityFallback[city]||chapters.find(c=>c.states?.includes(region)||c.provinces?.includes(region))?.id;return chapters.find(c=>c.id===byAddress)||chapters.find(c=>c.matches?.includes(person.chapter))||chapters[0];}
  function decorate(data){const node=document.querySelector('#chapter-context');if(!node)return;let person=null;try{const s=JSON.parse(localStorage.getItem('forest-community-v1')||'{}').session;person=data.people.find(p=>p.id===s.personaId);}catch{}const chapter=forPerson(person);node.innerHTML=`<a href="#chapter/${chapter.id}"><strong>${chapter.name}</strong> · ${person?.city||'National view'}</a>${person?'<a class="change" href="#profile" title="Chapter is inferred from your home city">change</a>':''}`;}
  root.ChapterCore={chapters,forPerson,decorate};
})(globalThis);
