/* Incremental dashboard views. Existing directory, relationships and events are reused. */
const Engagement = (()=>{
  'use strict';
  const core=CommunityCore;
  let repository,source;
  function init(data){source=data;if(!repository){let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error('Unavailable');},setItem(){throw Error('Unavailable');},removeItem(){throw Error('Unavailable');}};}repository=core.repository(storage,data.people.map(p=>p.id));}}
  const state=()=>repository.read();
  const name=id=>source.people.find(p=>p.id===id)?.name||'Demo member';
  function DashboardSection(title,description,body,action=''){
    return `<section class="dashboard-section"><div class="section-head"><div><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>${action}</div>${body}</section>`;
  }
  function SuggestedMemberCard(match){const p=match.person;return `<article class="suggestion-card"><div class="member-heading"><div class="avatar">${esc(initials(p.name))}</div><div><h3><a href="#person/${p.id}">${esc(p.name)}</a></h3><p>${esc(p.city)}</p></div></div><ul class="match-reasons">${match.reasons.slice(0,3).map(reason=>`<li>${esc(reason)}</li>`).join('')}</ul><div class="action-row"><button class="button secondary" data-community-action="save-person" data-target="${p.id}">Save introduction</button><button class="text-button" data-community-action="dismiss-person" data-target="${p.id}" aria-label="Dismiss suggestion for ${esc(p.name)}">Not now</button></div></article>`;}
  function GroupCard({group,shared}){const saved=state().savedGroups.includes(group.id);return `<article class="community-group-card"><p class="eyebrow">${esc(group.format)} · Example group</p><h3><a href="#community-group/${group.id}">${esc(group.name)}</a></h3><p>${esc(group.description)}</p><p class="group-match">${shared.length?`Matches your interests: ${shared.map(i=>esc(i.label)).join(', ')}`:'Explore a new interest'}</p><div class="action-row"><a href="#community-group/${group.id}">Explore group →</a><button class="text-button" data-community-action="${saved?'remove-group':'save-group'}" data-target="${group.id}">${saved?'Remove saved group':'Save group'}</button></div></article>`;}
  function localNotice(){return `<p class="demo-context">Personalized demo · Choices stay in this browser. Saving people or groups does not send invitations or create memberships. <a href="#preferences">Your preferences</a></p><p class="storage-status" role="status">${repository.isPersistent()?'':'Browser storage is unavailable. New choices last only until this page closes.'}</p>`;}
  function eventRow({event,date}){return `<a class="next-event" href="#event/${event.id}"><img src="${event.image}" alt="" width="100" height="75"><div><time datetime="${date}">${dateLabel(date)} · All day</time><h3>${esc(event.name)}</h3><p>${esc(event.location)}</p></div><span aria-hidden="true">↗</span></a>`;}
  function recentActivity(){const activity=state().activity;const verbs={'preferences':'You updated your demo preferences.','save-person':'You saved an introduction to','remove-person':'You removed a saved introduction to','dismiss-person':'You dismissed a suggestion for','save-group':'You saved the group','remove-group':'You removed the saved group'};return activity.length?`<ol class="local-activity">${activity.slice(0,5).map(a=>`<li><span>${esc(verbs[a.type])}${a.target?` ${esc(a.type.includes('person')?name(a.target):core.groups.find(g=>g.id===a.target)?.name)}.`:''}</span><time datetime="${esc(a.at)}">${new Date(a.at).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</time></li>`).join('')}</ol>`:'<p class="quiet-empty">Your saved introductions, group choices, and preference updates will appear here. No one else sees this activity.</p>';}
  function ContributionCard(){const chosen=core.capabilities.filter(c=>state().helpIds.includes(c.id));return `<article class="contribution-card"><span class="eyebrow">HOW CAN I HELP?</span><h3>${chosen.length?'You have something to share.':'A little help can start a connection.'}</h3><p>${chosen.length?`You chose ${chosen.map(c=>esc(c.label)).join(', ')}. Use these as conversation starters when you explore a gathering or group.`:'Choose a few ways you would enjoy helping—language practice, a warm welcome, or community volunteering.'}</p><p class="subtle">These preferences are not published as offers to other members.</p><a class="button" href="#preferences">${chosen.length?'Update ways to help':'Choose ways to help'}</a></article>`;}
  function home(data){init(data);const s=state(),upcoming=core.upcoming(data.events),matches=core.suggestions(data,s,2),groups=core.groupSuggestions(s).slice(0,2);
    main.innerHTML=`<div class="dashboard-heading"><div><p class="eyebrow">YOUR COMMUNITY, IN MOTION</p><h1>Know someone. Do something together.</h1><p class="sub">${s.personaId?`Exploring connections from ${esc(name(s.personaId))}’s demo profile.`:'Find a familiar face, a shared interest, and your next gathering.'}</p></div><a class="button secondary" href="#preferences">${s.personaId?'Edit preferences':'Personalize your view'}</a></div>${localNotice()}<div class="dashboard-layout"><div>${DashboardSection('Happening soon','The next dated gatherings in the 2027 demo programme.',upcoming.length?upcoming.slice(0,2).map(eventRow).join(''):'<p class="quiet-empty">No upcoming events are scheduled. Explore the calendar for the programme archive.</p>','<a href="#calendar">Calendar →</a>')}${DashboardSection('People you may want to know','Reasons come from visible demo fields, not AI or inferred private information.',matches.length?`<div class="suggestion-grid">${matches.map(SuggestedMemberCard).join('')}</div>`:`<div class="quiet-empty">${s.personaId?'You have reviewed the available suggestions. Browse the directory or reset dismissed suggestions in preferences.':'Choose a demo profile to explore people with shared languages and roots.'} <a href="#${s.personaId?'people':'preferences'}">${s.personaId?'Browse people':'Choose a demo profile'} →</a></div>`,'<a href="#suggestions">Explore suggestions →</a>')}</div><aside class="dashboard-aside">${ContributionCard()}<section class="next-steps"><h2>Your next steps</h2><ul><li>${s.personaId?'✓':'○'} <a href="#preferences">Choose a demo profile</a></li><li>${s.interestIds.length?'✓':'○'} <a href="#preferences">Choose your interests</a></li><li>${s.helpIds.length?'✓':'○'} <a href="#preferences">Choose ways to help</a></li><li>${s.savedGroups.length?'✓':'○'} <a href="#community-groups">Find a group to explore</a></li><li>${s.savedPeople.length?'✓':'○'} <a href="#suggestions">Save a possible introduction</a></li><li><a href="#connections">Explore family & connections →</a></li><li><a href="#events">Find a gathering →</a></li></ul></section></aside></div>${DashboardSection('Find your circle','Example groups to explore. Your selected interests bring relevant groups to the top.',`<div class="suggestion-grid">${groups.map(GroupCard).join('')}</div>`,'<a href="#community-groups">All groups →</a>')}${DashboardSection('Your recent activity','Only your actions in this browser.',recentActivity())}`;
    bind(()=>home(data));
  }
  function preferences(data){init(data);const s=state();const choices=(items,selected,field)=>items.map(item=>`<label class="choice"><input type="checkbox" name="${field}" value="${item.id}" ${selected.includes(item.id)?'checked':''}><span>${esc(item.label)}</span></label>`).join('');
    main.innerHTML=heading('Make this community view your own.','Explore with a fictional profile and choose interests that matter to you. No account or personal details are needed.','DEMO PREFERENCES')+localNotice()+`<form id="community-preferences" class="preferences-form"><fieldset><legend>1. Choose a demo profile</legend><p>This selects a viewpoint for recommendations. It does not sign you in or edit the source person.</p><label for="demo-persona">Demo profile</label><select id="demo-persona" name="persona"><option value="">Browse without a persona</option>${data.people.map(p=>`<option value="${p.id}" ${s.personaId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></fieldset><fieldset><legend>2. What interests you?</legend><p>Used to suggest example groups. These are your local preferences, not claims about the selected Ramayana character.</p><div class="choice-grid">${choices(core.interests,s.interestIds,'interest')}</div></fieldset><fieldset><legend>3. I can help with…</legend><p>Optional. Pick topics you would enjoy helping with. Nothing is published or sent to anyone.</p><div class="choice-grid">${choices(core.capabilities,s.helpIds,'help')}</div></fieldset><div class="action-row"><button class="button" type="submit">Save preferences</button><a href="#home">Back to My Community</a></div><p id="preferences-status" role="status"></p></form><section class="reset-preferences"><h2>Start fresh</h2><p>Clear demo preferences, saved introductions, saved groups, and local activity. Existing event bookmarks stay saved.</p><button id="reset-community" class="button secondary">Clear community preferences</button></section>`;
    document.querySelector('#community-preferences').onsubmit=event=>{event.preventDefault();const interestIds=Array.from(document.querySelectorAll('input[name="interest"]:checked'),el=>el.value),helpIds=Array.from(document.querySelectorAll('input[name="help"]:checked'),el=>el.value);repository.apply({type:'preferences',value:{personaId:document.querySelector('#demo-persona').value,interestIds,helpIds}});document.querySelector('#preferences-status').textContent=repository.isPersistent()?'Saved in this browser. Open My Community to see your suggestions.':'Updated for this visit only; browser storage is unavailable.';};
    document.querySelector('#reset-community').onclick=()=>{repository.reset();preferences(data);document.querySelector('#preferences-status').textContent=repository.isPersistent()?'Community preferences cleared.':'Preferences cleared for this visit; persistent browser storage could not be changed.';document.querySelector('#preferences-status').focus();};
  }
  function suggestions(data){init(data);const s=state(),matches=core.suggestions(data,s,12);main.innerHTML=heading('A reason to say hello.','Explore people through shared languages and places. Save an introduction to revisit it; nothing is sent.','PEOPLE & CONNECTIONS')+localNotice()+`<div class="suggestion-grid">${matches.map(SuggestedMemberCard).join('')||'<p class="quiet-empty">Choose a demo profile or reset dismissed suggestions in <a href="#preferences">preferences</a> to see introductions.</p>'}</div>`+DashboardSection('Saved introductions','For your next visit. These are not accepted connections.',s.savedPeople.length?`<div class="cards">${s.savedPeople.map(id=>`<article class="saved-introduction"><h3><a href="#person/${id}">${esc(name(id))}</a></h3><button class="text-button" data-community-action="remove-person" data-target="${id}">Remove saved introduction</button></article>`).join('')}</div>`:'<p class="quiet-empty">No introductions saved yet.</p>');bind(()=>suggestions(data));}
  function groups(data,id){init(data);if(id){const group=core.groups.find(g=>g.id===id);if(!group){main.innerHTML=heading('Group not found.','<a href="#community-groups">Browse example groups →</a>');return;}
      const match=core.groupSuggestions(state()).find(m=>m.group.id===id),event=data.events.find(e=>e.id===group.eventId);main.innerHTML=heading(esc(group.name),esc(group.description),'EXAMPLE GROUP')+localNotice()+GroupCard(match)+DashboardSection('A way to participate','An activity idea for a future organizer.',`<div class="note">${esc(group.activity)}<p>Organizer and member registration are not available in this public demo.</p></div>`)+DashboardSection('A related story to explore','This is an editorial connection to the demo programme, not an event hosted by this example group.',event?eventRow({event,date:event.dates[0]}):'<p>No related event.</p>');bind(()=>groups(data,id));return;}
    main.innerHTML=heading('Find your circle.','Explore small group concepts around shared interests. Save the ones you would like to revisit.','BRANCHES & GATHERINGS')+localNotice()+`<p class="inline-help">Heritage collections are still available in <a href="#groups">Lineages →</a></p><div class="suggestion-grid">${core.groupSuggestions(state()).map(GroupCard).join('')}</div>`;bind(()=>groups(data));
  }
  function bind(render){document.querySelectorAll('[data-community-action]').forEach(button=>{button.onclick=()=>{const action=button.dataset.communityAction;repository.apply({type:action,target:button.dataset.target});render();const status=document.querySelector('.storage-status');if(status){status.textContent=repository.isPersistent()?'Your choice was saved in this browser.':'Updated for this visit only; browser storage is unavailable.';status.setAttribute('tabindex','-1');status.focus();}};});}
  return {home,preferences,suggestions,groups,DashboardSection,SuggestedMemberCard,GroupCard,ContributionCard};
})();
