/* Searchable capability network; only explicit offers appear. */
const HelpNetwork=(()=>{
  'use strict';
  let repo;
  const capabilities=()=>CommunityCore.capabilities;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function repository(){if(!repo){let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error();},setItem(){throw Error();},removeItem(){throw Error();}};}repo=HelpCore.repository(storage,capabilities());}return repo;}
  function render(data,actor){
    const store=repository(),state=store.read(),own=HelpCore.offer(state,actor?.id,capabilities()),prompt=HelpCore.prompt(state,actor,capabilities());
    document.querySelector('#main').innerHTML=`<p class="eyebrow">HOW CAN WE HELP EACH OTHER?</p><h1>Find someone who can help.</h1><p class="sub">Explore members’ voluntary offers, or choose a way to contribute.</p><p class="demo-context">Fictional demo: offers are saved in this browser and appear when you switch members here. No requests or contact details are sent. ${store.isPersistent()?'':'Storage is unavailable; changes last for this visit only.'}</p>${actor?`<form id="help-offer-form" class="preferences-form"><fieldset><legend>I can help with</legend><p>Choose your topics. Availability must be on for your offer to appear to other demo members.</p><div class="choice-grid">${capabilities().map(c=>`<label><input type="checkbox" name="capabilities" value="${esc(c.id)}" ${own.capabilityIds.includes(c.id)?'checked':''}> ${esc(c.label)}</label>`).join('')}</div></fieldset><label for="help-available">Available to help?</label><select id="help-available" name="available"><option value="no" ${own.available?'':'selected'}>No — keep my topics for later</option><option value="yes" ${own.available?'selected':''}>Yes — show my offer in this demo</option></select><button class="button" type="submit">Save help preferences</button></form>${prompt?`<section class="help-prompt"><h2>${esc(prompt.title)}</h2><p>${esc(prompt.text)}</p>${prompt.available?'<a class="button secondary" href="#questions">Explore community questions →</a>':'<button type="button" class="button secondary" id="help-review">Update availability ↑</button>'}</section>`:''}`:'<p><a href="#login">Sign in</a> to choose ways you can help.</p>'}<p id="help-status" role="status"></p><section aria-labelledby="help-search-title"><h2 id="help-search-title">Find help</h2><div class="help-filters"><label>Topic<select id="help-topic"><option value="">All topics</option>${capabilities().map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('')}</select></label><label>City<select id="help-city"><option value="">All cities</option>${[...new Set(data.people.map(p=>p.city).filter(Boolean))].sort().map(city=>`<option>${esc(city)}</option>`).join('')}</select></label><label>Search<input id="help-query" type="search" placeholder="Name, city, or help topic"></label></div><p id="help-count" role="status"></p><div id="help-results" class="help-results"></div></section>`;
    const field=id=>document.getElementById(id);
    function results(){const matches=HelpCore.search(data.people,store.read(),capabilities(),{capabilityId:field('help-topic').value,city:field('help-city').value,query:field('help-query').value,viewerId:actor?.id||''});field('help-count').textContent=`${matches.length} available ${matches.length===1?'member':'members'}`;field('help-results').innerHTML=matches.map(({person,capabilities:topics})=>`<article class="help-card"><h3><a href="#person/${encodeURIComponent(person.id)}">${esc(person.name)}</a></h3><p>${esc(person.city)}</p><p class="help-availability">Available to help · Explicit demo opt-in</p><ul>${topics.map(c=>`<li>${esc(c.label)}</li>`).join('')}</ul><a class="button secondary" href="#person/${encodeURIComponent(person.id)}">View profile</a></article>`).join('')||'<p class="quiet-empty">No available offers match yet. Members must select topics and turn on availability. Switch demo members to try offering and finding help.</p>';}
    if(field('help-review'))field('help-review').onclick=()=>field('help-available').focus();
    field('help-topic').onchange=field('help-city').onchange=field('help-query').oninput=results;results();
    if(actor)field('help-offer-form').onsubmit=event=>{event.preventDefault();const selected=Array.from(document.querySelectorAll('#help-offer-form input:checked'),input=>input.value),available=field('help-available').value==='yes';if(available&&!selected.length){field('help-status').textContent='Choose at least one help topic before turning on availability.';return;}store.apply({type:'offer',available,capabilityIds:selected},actor);render(data,actor);field('help-status').textContent=store.isPersistent()?'Help preferences saved in this browser.':'Help preferences updated for this visit; storage is unavailable.';};
  }
  return {render,reset:()=>repository().reset(),activity:()=>repository().read().activity};
})();
