(function(root){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const journeyKey='forest-demo-journey-v1';
  const steps=[
    {id:'login',n:'01',title:'Sign in as Rama',body:'Rama is selected for you in the demo sign-in screen. Continue as him to load his home chapter, chapter theme, and highlighted convention.',tryHref:'#login/journey',tryLabel:'Continue with Rama selected'},
    {id:'register',n:'02',title:'Register for IMRC',body:'Open the highlighted IMRC Convention registration panel and register Rama’s household.',tryHref:'#event/EV2028/journey',tryLabel:'Open highlighted registration'},
    {id:'agenda',n:'03',title:'Pick agenda items',body:'Use the highlighted agenda checkboxes to build Rama’s personal schedule. Each choice saves without moving the page.',tryHref:'#event/EV2028/journey',tryLabel:'Open highlighted agenda'},
    {id:'profile',n:'04',title:'See it on his profile',body:'Return to Rama’s profile to see his chapter, selected sessions, reminders, and logistics in one place.',tryHref:'#profile/journey',tryLabel:'Open Rama’s profile'},
    {id:'participate',n:'05',title:'Build momentum',body:'Vote, ask a question, offer help, or check in. The activity feed and badges make participation visible.',tryHref:'#votes/journey',tryLabel:'Try a highlighted poll'}
  ];
  function read(key,fallback={}){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch{return fallback;}}
  function journeyState(){return read(journeyKey,{profileVisited:false});}
  function mark(name,value=true){const state=journeyState();state[name]=value;try{localStorage.setItem(journeyKey,JSON.stringify(state));}catch{}}
  function begin(step){mark('activeGuide',step);}
  function progress(){const community=read('forest-community-v1'),session=community.session||{},actions=read('forest-event-actions-v1'),registration=(actions.registrations||[]).some(r=>r.eventId==='EV2028'&&r.actorId==='RAM-001'),plan=(actions.conventionPlans||[]).find(p=>p.eventId==='EV2028'&&p.actorId==='RAM-001'),votes=read('forest-votes-v1'),participation=read('forest-participation-v1'),help=read('forest-help-v1'),recognition=read('forest-recognition-v1'),engaged=Object.keys(votes.votes||{}).length>0||(participation.activity||[]).length>0||(help.activity||[]).length>0||(recognition.activity||[]).length>0;return [session.authenticated&&session.personaId==='RAM-001',registration,(plan?.agendaIds||[]).length>0,journeyState().profileVisited&&registration,engaged];}
  function nextIndex(done){const index=done.findIndex(value=>!value);return index<0?steps.length-1:index;}
  function rail(done,current=-1){return `<ol class="journey-rail" aria-label="Member journey progress">${steps.map((step,index)=>`<li class="${done[index]?'done':''} ${index===current?'current':''}"><a href="${index===0&&current===0?step.tryHref:`#journey/${step.id}`}" ${index===current?'aria-current="step"':''}><span>${done[index]?'✓':step.n}</span>${esc(step.title)}</a></li>`).join('')}</ol>`;}
  function render(data){const main=document.querySelector('#main'),event=data?.events?.find(e=>e.id==='EV2028'),done=progress(),next=nextIndex(done);if(!main)return;document.body.classList.add('landing-mode');main.innerHTML=`<div class="demo-landing"><section class="demo-hero"><p class="landing-kicker">IMRC COMMUNITY · INTERACTIVE DEMO</p><h1>Follow Rama from hello to belonging.</h1><p class="landing-lede">Move through a real member journey: sign in, register for ${esc(event?.name||'the IMRC Convention')}, choose agenda items, and see participation grow on the profile.</p><div class="landing-actions"><a class="button landing-primary" href="#journey/${steps[next].id}">${done.some(Boolean)?'Continue Rama’s journey':'Start Rama’s journey'} →</a><span class="journey-score">${done.filter(Boolean).length} of ${steps.length} complete</span></div></section><section class="demo-workflow" aria-labelledby="workflow-title"><a class="red-marker journey-heading" href="#journey/${steps[next].id}"><span>01</span><h2 id="workflow-title">One member’s journey</h2><b>Open guided journey →</b></a>${rail(done)}</section><section class="demo-callout"><div><p class="eyebrow">WHY THE FEED MATTERS</p><h2>Participation becomes a story.</h2><p>Rama’s activity feed connects a completed action to the next invitation. Organizers can turn milestones into opt-in badges, recognition, and friendly challenges without publishing private logistics.</p></div><a class="button secondary" href="#votes">Try a community poll →</a></section><p class="landing-footnote">Everything in this tour is a fictional, browser-local demonstration. It does not register a real person, reserve a seat, or send notifications.</p></div>`;document.title='Rama’s member journey · Tree in the Forest';}
  function renderJourney(data,id='login'){const main=document.querySelector('#main');if(!main)return;const done=progress(),index=Math.max(0,steps.findIndex(step=>step.id===id)),step=steps[index],next=steps[index+1],event=data?.events?.find(e=>e.id==='EV2028');document.body.classList.add('landing-mode');main.innerHTML=`<div class="journey-page"><a class="journey-back" href="#start">← Member journey overview</a><div class="journey-layout"><aside><p class="landing-kicker">RAMA’S MEMBER JOURNEY</p><p class="journey-score">${done.filter(Boolean).length} of ${steps.length} complete</p>${rail(done,index)}</aside><section class="journey-step"><span class="workflow-number">STEP ${step.n}</span><h1>${esc(step.title)}</h1><p class="landing-lede">${esc(step.body)}</p><div class="journey-task"><p class="eyebrow">TRY IT IN THE DEMO</p><h2>${index===0?'Use Rama Ikshvaku’s fictional member account.':index===1?`Register for ${esc(event?.name||'IMRC Convention 2028')}.`:index===2?'Choose any agenda session and watch for the Saved pill.':index===3?'Confirm Rama’s chapter and convention plan on his profile.':'Cast a poll vote and return to see the activity feed.'}</h2><a class="button" data-journey-try="${step.id}" href="${step.tryHref}">${esc(step.tryLabel)} →</a></div><div class="journey-actions">${index?`<a href="#journey/${steps[index-1].id}">← Previous step</a>`:'<span></span>'}${next?`<a class="button secondary" data-journey-next href="#journey/${next.id}">Next: ${esc(next.title)} →</a>`:'<a class="button secondary" href="#profile/journey">Finish on Rama’s profile →</a>'}</div></section></div></div>`;main.querySelector('[data-journey-try]')?.addEventListener('click',()=>begin(step.id));main.querySelector('[data-journey-next]')?.addEventListener('click',()=>mark(`opened_${next.id}`));document.title=`${step.title} · Rama’s journey`;}
  function markRoute(view){if(view==='profile')mark('profileVisited');}
  root.DemoLanding={render,renderJourney,progress,markRoute,journeyState,mark,begin,steps};
  const main=document.querySelector('#main');if(main&&typeof MutationObserver==='function')new MutationObserver(()=>{if(!location.hash&&root.IMRCData&&!main.querySelector('.demo-landing'))render(root.IMRCData);}).observe(main,{childList:true,subtree:true});
})(globalThis);
