(function(root){
  'use strict';
  let mounted=false,map=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function load(src){return new Promise((resolve,reject)=>{if(document.querySelector(`script[src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  async function render(){const main=document.querySelector('#main');if(!main)return;main.innerHTML='<p class="eyebrow">REAL DATA · U.S. CENSUS BUREAU</p><h1>Where people really live.</h1><p class="sub">County-level population, median age, and sex estimates shown as an aggregate heat map. No individual-level data is used.</p><div id="locality-map" class="locality-map" role="img" aria-label="Heat map of United States county population"></div><p id="locality-status" class="results">Loading Census data…</p><div class="note" id="locality-source"></div>';try{await load('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js');await load('https://unpkg.com/leaflet.heat@0.2.0/dist/leaflet-heat.js');const response=await fetch('./locality-data.json');if(!response.ok)throw Error('locality data unavailable');const data=await response.json();document.querySelector('#locality-status').textContent=`${data.counties.length.toLocaleString()} US counties · Vintage ${data.sourceYear} estimates`;document.querySelector('#locality-source').textContent=`${data.source} Generated ${data.generated}.`;if(map)map.remove();map=L.map('locality-map',{scrollWheelZoom:false}).setView([39.8,-98.6],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:11,attribution:'© OpenStreetMap contributors'}).addTo(map);const maxLog=Math.log10(Math.max(...data.counties.map(c=>c.population)));L.heatLayer(data.counties.map(c=>[c.lat,c.lng,Math.log10(c.population)/maxLog]),{radius:16,blur:20,max:1,maxZoom:9}).addTo(map);data.counties.forEach(c=>L.circleMarker([c.lat,c.lng],{radius:4,weight:0,fillOpacity:.01}).bindPopup(`<div class="locality-popup"><h3>${esc(c.name)}</h3><p class="sub">${esc(c.state)}</p><dl><dt>Population</dt><dd>${c.population.toLocaleString()}</dd><dt>Median age</dt><dd>${c.medianAge} (M ${c.medianAgeMale} · F ${c.medianAgeFemale})</dd><dt>Sex</dt><dd>${c.pctFemale}% female · ${c.pctMale}% male</dd></dl></div>`).addTo(map));}catch{document.querySelector('#locality-status').textContent='Unable to load locality data. Refresh or regenerate the Census snapshot.';}}
  function observe(){if(mounted)return;mounted=true;const nav=document.querySelector('nav');if(nav&&!nav.querySelector('a[href="#localitymap"]'))nav.insertAdjacentHTML('beforeend','<a href="#localitymap">▲ <span>Locality Map</span></a>');const route=()=>{if(location.hash==='#localitymap'){document.body.classList.remove('landing-mode');render();}};window.addEventListener('hashchange',route);route();}
  root.LocalityMap={observe,render};
  if(typeof document!=='undefined')document.addEventListener('locality-map-ready',observe);
})(globalThis);
