/* Small local question and mentorship views; no messages leave this browser. */
const Participation=(()=>{
  const core=ParticipationCore,key='forest-participation-v1';let memory=null,persistent=true;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function read(){if(memory)return core.normalize(memory);try{return core.normalize(JSON.parse(localStorage.getItem(key)||'null'));}catch{persistent=false;return core.normalize(null);}}
  function apply(action,actor){const before=read();memory=core.transition(before,action,actor);const changed=JSON.stringify(before)!==JSON.stringify(memory);if(changed)try{localStorage.setItem(key,JSON.stringify(memory));persistent=true;}catch{persistent=false;}return changed;}
  const note=()=>`<p class="demo-context">Fictional demo: questions, replies, reports, and introductions stay in this browser. Reports are local markers; no moderator is notified.${persistent?'':' Storage is unavailable: changes last until this page closes.'}</p>`;
  const date=v=>Number.isFinite(Date.parse(v))?new Date(v).toLocaleDateString():'';
  function questions(data,actor,filter='',followed=false){
    const s=read(),m=core.member(s,actor?.id),rows=[...s.questions,...core.seeds];
    document.querySelector('#main').innerHTML=`<h1>Ask the community</h1>${note()}${actor?`<form id="participation-question" class="preferences-form"><h2>Start a useful conversation</h2><label for="q-title">Question</label><input id="q-title" name="title" maxlength="160" required><label for="q-description">Details</label><textarea id="q-description" name="description" maxlength="600" required></textarea><label for="q-category">Category</label><select id="q-category" name="category">${core.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><label for="q-tags">Tags (up to five, separated by commas)</label><input id="q-tags" name="tags" maxlength="150" placeholder="welcome, local"><button class="button">Post question</button></form>`:'<p><a href="#login">Sign in as a fictional member</a> to ask, answer, follow, or react.</p>'}<label for="q-filter">Filter category</label><select id="q-filter"><option value="">All categories</option>${core.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select>${actor?`<label><input id="q-followed" type="checkbox" ${followed?'checked':''}> Only questions I follow</label>`:''}<div id="question-results"></div><p id="participation-status" role="status"></p>`;
    document.querySelector('#q-filter').value=filter;function rerender(){questions(data,actor,document.querySelector('#q-filter').value,Boolean(document.querySelector('#q-followed')?.checked));}function render(){const category=document.querySelector('#q-filter').value,onlyFollowed=Boolean(document.querySelector('#q-followed')?.checked);document.querySelector('#question-results').innerHTML=rows.filter(q=>(!category||q.category===category)&&(!onlyFollowed||m.following.includes(q.id))).map(q=>`<article class="question-card"><span class="tag">${esc(q.category)}</span><h2>${esc(q.title)}</h2><p>${esc(q.description)}</p><p>${q.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</p><p>Asked by ${esc(q.author)} · ${esc(date(q.date))}</p>${s.replies.filter(r=>r.questionId===q.id).map(r=>`<blockquote><p>${esc(r.body)}</p><footer>${esc(r.author)} · ${esc(date(r.date))}</footer></blockquote>`).join('')}${actor?`<div class="action-row">${[['following','Following','Follow / save'],['liked','Reacted','React'],['reported','Reported locally','Report locally']].map(([type,on,off])=>`<button class="button secondary" data-q-action="${type}" data-q-id="${esc(q.id)}" aria-pressed="${m[type].includes(q.id)}">${m[type].includes(q.id)?on:off}</button>`).join('')}</div><form data-reply="${esc(q.id)}"><label for="reply-${esc(q.id)}">Your reply</label><textarea id="reply-${esc(q.id)}" name="body" required maxlength="600"></textarea><button class="button">Post reply</button></form>`:''}</article>`).join('')||'<p>No questions in this category yet.</p>';document.querySelectorAll('[data-q-action]').forEach(b=>b.onclick=()=>{const changed=apply({type:b.dataset.qAction,target:b.dataset.qId},actor);rerender();if(!changed)document.querySelector('#participation-status').textContent='This action could not be saved; the local limit may have been reached.';});document.querySelectorAll('[data-reply]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const body=new FormData(f).get('body');if(!body.trim())return;const added=apply({type:'reply',target:f.dataset.reply,body},actor);if(added)rerender();document.querySelector('#participation-status').textContent=added?'Reply added.':'Reply could not be added. The local limit is 500 replies.';});}
    document.querySelector('#q-filter').onchange=render;if(document.querySelector('#q-followed'))document.querySelector('#q-followed').onchange=render;render();
    const form=document.querySelector('#participation-question');if(form)form.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));if(!values.title.trim()||!values.description.trim())return;const added=apply({type:'post',...values,tags:values.tags.split(',').map(t=>t.trim()),id:`q-${crypto.randomUUID()}`},actor);if(added)questions(data,actor);document.querySelector('#participation-status').textContent=added?'Question added.':'Question could not be added. The local limit is 100 questions.';};
  }
  function mentorship(data,actor,filter=''){
    const s=read(),m=core.member(s,actor?.id);
    document.querySelector('#main').innerHTML=`<h1>Mentorship</h1>${note()}<p>Offers are voluntary. Shared mentoring topics and city explain the order of suggestions. Saved introductions are reminders; they send no request.</p>${actor?`<form id="mentor-preferences" class="preferences-form"><h2>Your mentoring preferences</h2><label><input type="checkbox" name="willing" ${m.willing?'checked':''}> I am willing to mentor</label><label><input type="checkbox" name="seeking" ${m.seeking?'checked':''}> I am interested in a mentor</label><fieldset><legend>Mentoring areas</legend><div class="choice-grid">${core.areas.map(a=>`<label><input type="checkbox" name="areas" value="${esc(a)}" ${m.areas.includes(a)?'checked':''}> ${esc(a)}</label>`).join('')}</div></fieldset><button class="button">Save mentoring preferences</button></form>`:'<p><a href="#login">Sign in</a> to offer mentoring and save introductions.</p>'}<label for="mentor-filter">Mentoring topic</label><select id="mentor-filter"><option value="">All topics</option>${core.areas.map(a=>`<option>${esc(a)}</option>`).join('')}</select><div id="mentor-results" class="mentor-grid"></div><p id="participation-status" role="status"></p>`;
    function render(){const matches=core.matches(data.people,s,actor?.id,document.querySelector('#mentor-filter').value);document.querySelector('#mentor-results').innerHTML=matches.map(match=>`<article class="mentor-card"><h2><a href="#person/${esc(match.person.id)}">${esc(match.person.name)}</a></h2><p>${match.areas.map(esc).join(' · ')}</p><ul>${match.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>${actor?`<button class="button secondary" data-save-mentor="${esc(match.person.id)}" aria-pressed="${m.mentors.includes(match.person.id)}">${m.mentors.includes(match.person.id)?'Remove saved introduction':'Save introduction'}</button>`:''}</article>`).join('')||'<p>No matching offers yet. To try the demo, sign in as another member, opt in to mentoring, then return to your profile.</p>';document.querySelectorAll('[data-save-mentor]').forEach(b=>b.onclick=()=>{const topic=document.querySelector('#mentor-filter').value,changed=apply({type:'mentor',target:b.dataset.saveMentor},actor);mentorship(data,actor,topic);if(!changed)document.querySelector('#participation-status').textContent='Introduction could not be saved. The local limit is 100 introductions.';});}
    document.querySelector('#mentor-filter').value=filter;document.querySelector('#mentor-filter').onchange=render;render();const form=document.querySelector('#mentor-preferences');if(form)form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);apply({type:'mentorship',willing:f.has('willing'),seeking:f.has('seeking'),areas:f.getAll('areas')},actor);mentorship(data,actor);document.querySelector('#participation-status').textContent='Mentoring preferences saved.';};
  }
  function activity(){return read().activity;}
  function reset(){memory=core.normalize(null);try{localStorage.removeItem(key);persistent=true;}catch{persistent=false;}}
  return {questions,mentorship,activity,reset};
})();
