const Recognition=(()=>{
 'use strict';
 const core=RecognitionCore;let repo,ids=[];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function init(data){const next=data.people.map(p=>p.id);if(!repo){let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error();},setItem(){throw Error();},removeItem(){throw Error();}};}ids=next;repo=core.repository(storage,ids);}else{ids.splice(0,ids.length,...next);}}
 function render(data,actor){init(data);const state=repo.read(),person=id=>data.people.find(p=>p.id===id),validActor=actor&&ids.includes(actor.id)?actor:null;
 document.querySelector('#main').innerHTML=`<div class="recognition"><p class="eyebrow">MEMBER SPOTLIGHTS</p><h1>Small acts. Lasting connections.</h1><p>Celebrate someone who helped, welcomed, taught, or brought people together.</p><p class="demo-context">These are imagined editorial stories about fictional profiles. Nominations and thanks stay in this browser; nominations are not published or sent to an administrator.</p>${!repo.isPersistent()?'<p role="status">Browser storage is unavailable. Changes last only until this page closes.</p>':''}<div class="recognition-grid">${core.stories.filter(st=>person(st.memberId)).map(st=>{const p=person(st.memberId),thanked=state.thanks.some(t=>t.actorId===validActor?.id&&t.storyId===st.id);return `<article class="recognition-card"><p class="tag">${esc(st.category)} · Fictional spotlight</p><h2>${esc(st.title)}</h2><a href="#person/${esc(p.id)}">${esc(p.name)}</a><p>${esc(st.body)}</p>${validActor?`<button class="button secondary" data-thank="${st.id}" ${thanked?'disabled':''}>${thanked?'Appreciation saved':'Send local appreciation'}</button>`:''}</article>`;}).join('')}</div>${validActor?`<section><h2>Nominate a member</h2><form id="recognition-form"><label for="recognition-person">Who would you like to recognise?</label><select id="recognition-person" name="memberId" required><option value="">Choose a member</option>${data.people.filter(p=>p.id!==validActor.id).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><label for="recognition-category">Contribution</label><select id="recognition-category" name="category">${core.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><label for="recognition-reason">What did they do, and how did it help?</label><textarea id="recognition-reason" name="reason" required maxlength="600" rows="4"></textarea><button class="button">Save nomination locally</button></form><h2>Your nominations</h2>${state.nominations.filter(n=>n.authorId===validActor.id).map(n=>`<article class="recognition-card"><h3>${esc(person(n.memberId)?.name)}</h3><p class="tag">${esc(n.category)} · Local draft</p><p>${esc(n.reason)}</p></article>`).join('')||'<p>No nominations yet. One thoughtful thank-you is a good place to start.</p>'}</section>`:'<p><a href="#login">Sign in as a fictional member</a> to nominate someone or save appreciation.</p>'}<p id="recognition-status" role="status"></p></div>`;
 document.querySelectorAll('[data-thank]').forEach(button=>button.onclick=()=>{repo.apply({type:'thank',storyId:button.dataset.thank},validActor.id);render(data,validActor);document.querySelector('#recognition-status').textContent='Appreciation saved in this browser.';});
 const form=document.querySelector('#recognition-form');if(form)form.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form)),before=repo.read().nominations.length;if(!values.reason.trim()){document.querySelector('#recognition-status').textContent='Please describe their contribution.';return;}repo.apply({type:'nominate',...values},validActor.id);const added=repo.read().nominations.length>before;render(data,validActor);document.querySelector('#recognition-status').textContent=added?'Nomination saved as a local draft.':'You already nominated this member for that contribution, or the local draft limit has been reached.';};
 }
 function reset(){if(repo)repo.reset();else try{localStorage.removeItem(core.key);}catch{}}
 function activity(){return repo?repo.read().activity.map(a=>({...a,text:a.type==='nominate'?'Saved a member nomination':'Saved appreciation for a member spotlight'})):[];}
 return {render,reset,activity,init};
})();
